### ISSUE TITLE
Redis cache incompatibility

### ISSUE THREAD

**Issue by kissit** [pocketarc/codeigniter#10]
It looks like the version of `system/libraries/Cache/drivers/Cache_redis.php` in the fork was being re-worked in the source develop branch and is throwing the following warning.  Furthermore, even just fixing the warning, I don't think the code looks complete (no setting of TTL in the save function for instance, also increment/decrement wouldn't really fit the new way of storing the keys/data types/values).

I ended up just reverting the entire file from the prior 3.1.13 release which seems to work as expected, but didn't know if that was the desired fix for you.

```
A PHP Error was encountered
Severity: Warning

Message: Undefined variable $value

Filename: drivers/Cache_redis.php

Line Number: 166
```

**Comment by siemova** [comment]
I opened a PR after encountering the same problem. However, I'd suggest that it might be a good idea to fork and maintain the source repo's master branch—whether instead of or in addition to the development branch—for users who don't want (or expect!) any WIP changes like these. I certainly appreciate what's been done already, though!

**Comment by pocketarc** [comment]
@siemova Merged, thank you very much for your help!
